# Generated by Django 4.2.13 on 2024-06-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('umbral', models.PositiveIntegerField(default=5)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
