# Generated by Django 4.2.13 on 2024-06-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=10)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('edad', models.IntegerField()),
                ('nHistoriaClinica', models.CharField(max_length=20, unique=True)),
                ('motivoConsulta', models.TextField()),
                ('enfermedad', models.TextField()),
                ('antecedentesPersonales', models.TextField()),
                ('signosVitales', models.TextField()),
                ('sistemaEstomatognatico', models.TextField()),
                ('saludBucal', models.TextField()),
                ('indicesCPO', models.TextField()),
                ('diagnostico', models.TextField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
