# Generated by Django 4.2.13 on 2024-06-27 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HistoriaClinica', '0001_initial'),
        ('odontologo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='idOdontologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontologo.odontologo'),
        ),
    ]
