# Generated by Django 4.2.13 on 2024-06-27 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
        ('odontologo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('duracion', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='confirmada', max_length=10)),
                ('servicio', models.CharField(choices=[('sin servicio', 'Sin Servicio'), ('con servicio', 'Con Servicio')], default='sin servicio', max_length=20)),
                ('idOdontologo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='odontologo.odontologo')),
                ('idPaciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
    ]
