# Generated by Django 4.2.13 on 2024-07-01 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_cita_servicios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='servicios',
            new_name='servic',
        ),
    ]
