# Generated by Django 4.2.13 on 2024-07-01 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
        ('cita', '0003_rename_servicios_cita_servic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='servic',
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio_opcion',
            field=models.CharField(choices=[('sin servicio', 'Sin Servicio'), ('con servicio', 'Con Servicio')], default='sin servicio', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.servicio'),
        ),
    ]
