# Generated by Django 4.2.13 on 2024-07-01 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0005_remove_cita_servicio_opcion_cita_servic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='servic',
        ),
    ]
