# Generated by Django 4.2.13 on 2024-06-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontologo',
            name='llave',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
