# Generated by Django 4.2.13 on 2024-07-02 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('odontologo', '0002_odontologo_llave'),
        ('paciente', '0001_initial'),
        ('car', '0003_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='idOdontologo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='odontologo.odontologo'),
        ),
        migrations.AddField(
            model_name='cart',
            name='idPaciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
    ]
