# Generated by Django 4.2.13 on 2024-06-27 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
        ('odontologo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radiografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='photos/radiografias')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('idOdontologo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='odontologo.odontologo')),
                ('idPaciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
    ]
